name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      name:
        type: text
        description: 'Person to greet'
        default: 'User Name'
        required: true
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello"
        echo " World" 
