name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      name:
        type: text
        description: 'Person to greet'
        default: 'User Name'
        required: true
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Testing API EndPoints
    - run: echo "Hello World!!!!"
